# Generated by Django 5.2.4 on 2025-07-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
